version: '3'

services:
#  application:
#    container_name: application
#    build:
#      context: .
#      dockerfile: Dockerfile
#    ports:
#      - '3000:3000'
#    command:
#      - /bin/bash -c "npm run serve"
  nodejs:
    container_name: nodejs
    image: node:18.10.0-slim
    command: /bin/bash -c "npm i && npm run build && npm run serve"
    working_dir: /home/node
    volumes:
      - .:/home/node
    ports:
      - '8081:8080'