version: '3'

services:
  nodejs:
    container_name: nodejs
    image: node:18.10.0-slim
    command: /bin/bash -c "npm i && npm run build && npm run serve"
    working_dir: /home/node
    volumes:
      - .:/home/node
    ports:
      - '8081:8080'